#ifndef SCEDITCONTROLLER_GLOBAL_H
#define SCEDITCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCEDITCONTROLLER_LIBRARY)
#  define SCEDITCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCEDITCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCEDITCONTROLLER_GLOBAL_H
