// This header file was generated using VisualSC's Export Code Function

// Visual Statechart is an open source project. Visit us at https://github.com/daviddrell/visualsc
#ifndef A_H
#define A_H

#include <QObject>
#include <QStateMachine>
#include <QFinalState>

class A : public QObject
{
    Q_OBJECT

    //////////////////
    //
    //    Public interface
    //
    //    Connect to public slots to drive events into
    //    the state machine
    //
    //    Connect to the public signals to do work
    //    and monitor state changes
    //
    //////////////////

public:
    A(QObject*parent=NULL);
    ~A();

    //
    //    INPUT EVENT SLOTS
    //
    //    Call these slots to signal event inputs to the machine
    //


public slots:
    //////// State Machine: _a___3fa67e8e ////////
    void Event_startMachine_a___3fa67e8e();


signals:
    //
    //    OUTPUT ACTION SIGNALS
    //
    //    Connect to these signals to a slot corresponding to a entryAction or exitAction
    //
    //////// State Machine: _a___3fa67e8e ////////


    //
    //    STATE CHANGE MONITOR SIGNALS
    //
    //    Connect to these signals to monitor state transitions
    //
    //////// State Machine: _a___3fa67e8e ////////
    void Signal_StateReady_a___3fa67e8e();
    void Signal_StateEntry_a___55ac6a18();
    void Signal_StateExit_a___55ac6a18();
    void Signal_StateEntry_a___ab81a686();
    void Signal_StateExit_a___ab81a686();
    void Signal_StateEntry_a___c67f423a();
    void Signal_StateExit_a___c67f423a();


    //////////////////
    //
    //    Private below here
    //
    //////////////////


    /*
     *  A consequence of OOB encapsulation is that this class does know about its users, and so cannot listen
     * to their signals. Therefore this class exposes public slots that users can call. These slots
     * are then translated into private signals that the private state machine can listen to.
     *
     * For outbound signals, I choose to keep the statemachine objects private so that means I need
     * to translate private state machine signals into public signals.
     *
     * This all leads to a lot of confusion and possible name collisions. Therefore its better for this
     * file to be autogenerated from the visual state chart editor.
     *
     */


private:


private slots:
    // The Entry/Exit Slots that belong to QStates
    //////// State Machine: _a___3fa67e8e ////////
    void Slot_StateEntry_a___55ac6a18();
    void Slot_StateExit_a___55ac6a18();
    void Slot_StateEntry_a___ab81a686();
    void Slot_StateExit_a___ab81a686();
    void Slot_StateEntry_a___c67f423a();
    void Slot_StateExit_a___c67f423a();


signals:
    // A Transition/Event slot's corresponding signal emitted in the slot
    //////// State Machine: _a___3fa67e8e ////////


private:
    //////// State Machine: _a___3fa67e8e ////////
    QStateMachine*    _a___3fa67e8e;
    QState*    _a___55ac6a18;
    QState*    _a___ab81a686;
    QState*    _a___c67f423a;


};

#endif // A_H
