// This header file was generated using VisualSC's Export Code Function

// Visual Statechart is an open source project. Visit us at https://github.com/daviddrell/visualsc
#ifndef STATESEQUENCEMACHINE_H
#define STATESEQUENCEMACHINE_H

#include <QObject>
#include <QStateMachine>
#include <QFinalState>

class StateSequenceMachine : public QObject
{
    Q_OBJECT

    //////////////////
    //
    //    Public interface
    //
    //    Connect to public slots to drive events into
    //    the state machine
    //
    //    Connect to the public signals to do work
    //    and monitor state changes
    //
    //////////////////

public:
    StateSequenceMachine(QObject*parent=NULL);
    ~StateSequenceMachine();

    //
    //    INPUT EVENT SLOTS
    //
    //    Call these slots to signal event inputs to the machine
    //


public slots:
    //////// State Machine: _stateSequenceMachine ////////
    void Event_startMachine___stateSequenceMachine();
    void Event___checkingAllStatesCompleted();
    void Event___checkingCallSequenceFailed();
    void Event___checkingConnSequenceFailed();
    void Event___checkingSessionSeqFailed();

    //////// State Machine: _checkingAllStateSequences ////////

    //////// State Machine: _checkingCallSequence ////////
    void Event___callSeqComplete();

    //////// State Machine: _checkingConnSequence ////////
    void Event___connSeqComplete();

    //////// State Machine: _checkingSessionSeq ////////
    void Event___sessionSeqComplete();


signals:
    //
    //    OUTPUT ACTION SIGNALS
    //
    //    Connect to these signals to a slot corresponding to a entryAction or exitAction
    //
    //////// State Machine: _stateSequenceMachine ////////

    //////// State Machine: _checkingAllStateSequences ////////

    //////// State Machine: _checkingCallSequence ////////

    //////// State Machine: _checkingConnSequence ////////

    //////// State Machine: _checkingSessionSeq ////////


    //
    //    STATE CHANGE MONITOR SIGNALS
    //
    //    Connect to these signals to monitor state transitions
    //
    //////// State Machine: _stateSequenceMachine ////////
    void Signal_StateReady___stateSequenceMachine();
    void Signal_StateEntry___checkingAllStateSequences();
    void Signal_StateExit___checkingAllStateSequences();
    void Signal_StateEntry___failed();
    void Signal_StateExit___failed();
    void Signal_StateEntry___success();
    void Signal_StateExit___success();

    //////// State Machine: _checkingAllStateSequences ////////
    void Signal_StateEntry___checkingCallSequence();
    void Signal_StateExit___checkingCallSequence();
    void Signal_StateEntry___checkingConnSequence();
    void Signal_StateExit___checkingConnSequence();
    void Signal_StateEntry___checkingSessionSeq();
    void Signal_StateExit___checkingSessionSeq();

    //////// State Machine: _checkingCallSequence ////////
    void Signal_StateEntry___waiting_checkingCallSequence();
    void Signal_StateExit___waiting_checkingCallSequence();
    void Signal_StateEntry___completed_checkingCallSequence();
    void Signal_StateExit___completed_checkingCallSequence();

    //////// State Machine: _checkingConnSequence ////////
    void Signal_StateEntry___waiting_checkingConnSequence();
    void Signal_StateExit___waiting_checkingConnSequence();
    void Signal_StateEntry___completed_checkingConnSequence();
    void Signal_StateExit___completed_checkingConnSequence();

    //////// State Machine: _checkingSessionSeq ////////
    void Signal_StateEntry___waiting();
    void Signal_StateExit___waiting();
    void Signal_StateEntry___completed();
    void Signal_StateExit___completed();


    //////////////////
    //
    //    Private below here
    //
    //////////////////


    /*
     *  A consequence of OOB encapsulation is that this class does know about its users, and so cannot listen
     * to their signals. Therefore this class exposes public slots that users can call. These slots
     * are then translated into private signals that the private state machine can listen to.
     *
     * For outbound signals, I choose to keep the statemachine objects private so that means I need
     * to translate private state machine signals into public signals.
     *
     * This all leads to a lot of confusion and possible name collisions. Therefore its better for this
     * file to be autogenerated from the visual state chart editor.
     *
     */


private:


private slots:
    // The Entry/Exit Slots that belong to QStates
    //////// State Machine: _stateSequenceMachine ////////
    void Slot_StateEntry___checkingAllStateSequences();
    void Slot_StateExit___checkingAllStateSequences();
    void Slot_StateEntry___failed();
    void Slot_StateExit___failed();
    void Slot_StateEntry___success();
    void Slot_StateExit___success();

    //////// State Machine: _checkingAllStateSequences ////////
    void Slot_StateEntry___checkingCallSequence();
    void Slot_StateExit___checkingCallSequence();
    void Slot_StateEntry___checkingConnSequence();
    void Slot_StateExit___checkingConnSequence();
    void Slot_StateEntry___checkingSessionSeq();
    void Slot_StateExit___checkingSessionSeq();

    //////// State Machine: _checkingCallSequence ////////
    void Slot_StateEntry___waiting_checkingCallSequence();
    void Slot_StateExit___waiting_checkingCallSequence();
    void Slot_StateEntry___completed_checkingCallSequence();
    void Slot_StateExit___completed_checkingCallSequence();

    //////// State Machine: _checkingConnSequence ////////
    void Slot_StateEntry___waiting_checkingConnSequence();
    void Slot_StateExit___waiting_checkingConnSequence();
    void Slot_StateEntry___completed_checkingConnSequence();
    void Slot_StateExit___completed_checkingConnSequence();

    //////// State Machine: _checkingSessionSeq ////////
    void Slot_StateEntry___waiting();
    void Slot_StateExit___waiting();
    void Slot_StateEntry___completed();
    void Slot_StateExit___completed();


signals:
    // A Transition/Event slot's corresponding signal emitted in the slot
    //////// State Machine: _stateSequenceMachine ////////
    void Relay_Event___checkingAllStatesCompleted_checkingAllStateSequences();
    void Relay_Event___checkingCallSequenceFailed_checkingAllStateSequences();
    void Relay_Event___checkingConnSequenceFailed_checkingAllStateSequences();
    void Relay_Event___checkingSessionSeqFailed_checkingAllStateSequences();

    //////// State Machine: _checkingAllStateSequences ////////

    //////// State Machine: _checkingCallSequence ////////
    void Relay_Event___callSeqComplete_waiting_checkingCallSequence();

    //////// State Machine: _checkingConnSequence ////////
    void Relay_Event___connSeqComplete_waiting_checkingConnSequence();

    //////// State Machine: _checkingSessionSeq ////////
    void Relay_Event___sessionSeqComplete_waiting();


private:
    //////// State Machine: _stateSequenceMachine ////////
    QStateMachine*    _stateSequenceMachine;
    QState*    _checkingAllStateSequences;
    QFinalState*    _failed;
    QFinalState*    _success;

    //////// State Machine: _checkingAllStateSequences ////////
    // child QState declared elsewhere _checkingAllStateSequences
    QState*    _checkingCallSequence;
    QState*    _checkingConnSequence;
    QState*    _checkingSessionSeq;

    //////// State Machine: _checkingCallSequence ////////
    // child QState declared elsewhere _checkingCallSequence
    QState*    _waiting_checkingCallSequence;
    QFinalState*    _completed_checkingCallSequence;

    //////// State Machine: _checkingConnSequence ////////
    // child QState declared elsewhere _checkingConnSequence
    QState*    _waiting_checkingConnSequence;
    QFinalState*    _completed_checkingConnSequence;

    //////// State Machine: _checkingSessionSeq ////////
    // child QState declared elsewhere _checkingSessionSeq
    QState*    _waiting;
    QFinalState*    _completed;


};

#endif // STATESEQUENCEMACHINE_H
