// This header file was generated using VisualSC's Export Code Function

// Visual Statechart is an open source project. Visit us at https://github.com/daviddrell/visualsc
#ifndef STATEMACHINE_H
#define STATEMACHINE_H

#include <QObject>
#include <QStateMachine>
#include <QFinalState>

class StateMachine : public QObject
{
    Q_OBJECT

    //////////////////
    //
    //    Public interface
    //
    //    Connect to public slots to drive events into
    //    the state machine
    //
    //    Connect to the public signals to do work
    //    and monitor state changes
    //
    //////////////////

public:
    StateMachine(QObject*parent=NULL);
    ~StateMachine();

    //
    //    INPUT EVENT SLOTS
    //
    //    Call these slots to signal event inputs to the machine
    //


public slots:
    //////// State Machine: _stateMachine ////////
    void Event_startMachine___stateMachine();
    void Event___event_a();
    void Event___sr_b();

    //////// State Machine: _a ////////
    void Event___xToY_x_a();

    //////// State Machine: _b ////////


signals:
    //
    //    OUTPUT ACTION SIGNALS
    //
    //    Connect to these signals to a slot corresponding to a entryAction or exitAction
    //
    //////// State Machine: _stateMachine ////////
    void EntryAction___jump();
    void EntryAction___sleep();
    void EntryAction___dance();
    void ExitAction___fall();
    void ExitAction___down();
    void ExitAction___into();

    //////// State Machine: _a ////////

    //////// State Machine: _b ////////


    //
    //    STATE CHANGE MONITOR SIGNALS
    //
    //    Connect to these signals to monitor state transitions
    //
    //////// State Machine: _stateMachine ////////
    void Signal_StateReady___stateMachine();
    void Signal_StateEntry___a();
    void Signal_StateExit___a();
    void Signal_StateEntry___b();
    void Signal_StateExit___b();

    //////// State Machine: _a ////////
    void Signal_StateEntry___x_a();
    void Signal_StateExit___x_a();
    void Signal_StateEntry___y();
    void Signal_StateExit___y();

    //////// State Machine: _b ////////
    void Signal_StateEntry___x_b();
    void Signal_StateExit___x_b();


    //////////////////
    //
    //    Private below here
    //
    //////////////////


    /*
     *  A consequence of OOB encapsulation is that this class does know about its users, and so cannot listen
     * to their signals. Therefore this class exposes public slots that users can call. These slots
     * are then translated into private signals that the private state machine can listen to.
     *
     * For outbound signals, I choose to keep the statemachine objects private so that means I need
     * to translate private state machine signals into public signals.
     *
     * This all leads to a lot of confusion and possible name collisions. Therefore its better for this
     * file to be autogenerated from the visual state chart editor.
     *
     */


private:


private slots:
    // The Entry/Exit Slots that belong to QStates
    //////// State Machine: _stateMachine ////////
    void Slot_StateEntry___a();
    void Slot_StateExit___a();
    void Slot_StateEntry___b();
    void Slot_StateExit___b();

    //////// State Machine: _a ////////
    void Slot_StateEntry___x_a();
    void Slot_StateExit___x_a();
    void Slot_StateEntry___y();
    void Slot_StateExit___y();

    //////// State Machine: _b ////////
    void Slot_StateEntry___x_b();
    void Slot_StateExit___x_b();


signals:
    // A Transition/Event slot's corresponding signal emitted in the slot
    //////// State Machine: _stateMachine ////////
    void Relay_Event___event_a();
    void Relay_Event___sr_b();

    //////// State Machine: _a ////////
    void Relay_Event___xToY_x_a();

    //////// State Machine: _b ////////


private:
    //////// State Machine: _stateMachine ////////
    QStateMachine*    _stateMachine;
    QState*    _a;
    QState*    _b;

    //////// State Machine: _a ////////
    // child QState declared elsewhere _a
    QState*    _x_a;
    QFinalState*    _y;

    //////// State Machine: _b ////////
    // child QState declared elsewhere _b
    QState*    _x_b;


};

#endif // STATEMACHINE_H
