#ifndef SCGRAPHICSVIEW_GLOBAL_H
#define SCGRAPHICSVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCGRAPHICSVIEW_LIBRARY)
#  define SCGRAPHICSVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCGRAPHICSVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCGRAPHICSVIEW_GLOBAL_H
