#ifndef SCDATAMODEL_GLOBAL_H
#define SCDATAMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCDATAMODEL_LIBRARY)
#  define SCDATAMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCDATAMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCDATAMODEL_GLOBAL_H
